### ISSUE TITLE
下划线高度位置怎么改变

### ISSUE THREAD

**Issue by ouluqiang** [zjw-swun/AppOrder#2]
下划线默认是在控件的底部位置，我想让下划线离底部有10个dp的间隔要怎么改

**Comment by zjw-swun** [comment]
设置自定义view，参考item_tab.xml的使用

**Comment by zjw-swun** [comment]
@ouluqiang 

设置自定义view，参考item_tab.xml的使用
--

**Comment by zjw-swun** [comment]
@ouluqiang 下划线位置 修改可以自行修改如下代码
canvas.drawRect(mIndicatorLeft, getHeight() - mSelectedIndicatorHeight,
                            mIndicatorRight, getHeight(), mSelectedIndicatorPaint);

**Comment by zjw-swun** [comment]
@ouluqiang 可以自行修改tablayout类的draw方法 的canvas.drawRect 中参数

**Comment by zjw-swun** [comment]
@ouluqiang 你的需求不常用，就不更新代码了哈，可以自行修改
