### ISSUE TITLE
在appcompat-v7:28.0.0版本不显示 底部 滑动栏了

### ISSUE THREAD

**Issue by lianghuiyong** [zjw-swun/AppOrder#3]

**Comment by zjw-swun** [comment]
@lianghuiyong 目前我们的app supportLibVersion也是28.0.0 是正常的

**Comment by lianghuiyong** [comment]
嗯嗯，看到了，新版的库改了，要在xml里设置高度，以前不用设置高度的
`app:tabIndicatorHeight="@dimen/2dp"`
